#pragma once

#include "orderbook/price_level.h"
#include "orderbook/types.h"

#include <unordered_map>
#include <vector>

namespace orderbook {

/// Limit order book with integer-tick price indexing.
///
/// # Why not std::map<double, PriceLevel>?
///
/// The naive approach — `std::map<double, PriceLevel>` — has two
/// fundamental problems:
///
/// 1. **Floating-point equality is unreliable.** IEEE 754 rounding means
///    `1.01 + 1.01 + 1.01 != 3.03` on most platforms. Using `double` as
///    a map key requires epsilon-based comparison, which breaks
///    strict weak ordering and produces undefined behavior in std::map.
///
/// 2. **Red-black tree cache locality is poor.** std::map nodes are
///    heap-allocated and pointer-chased. Walking the bid or ask side
///    to find the best price touches memory locations scattered across
///    the heap. At L1/L2 cache sizes this dominates latency.
///
/// # This implementation
///
/// Prices are integer ticks. The book uses a flat `std::vector<PriceLevel>`
/// indexed by `(price_ticks - base_price)`, giving O(1) price level
/// lookup. Bid/ask best prices are tracked as integers and updated on
/// every insert/cancel/fill — no tree traversal needed.
///
/// The tradeoff is memory: the vector is pre-allocated for the full
/// tick range [base_price, base_price + num_levels). For equities with
/// $0.01 ticks and a $100 price range, this is 10,000 levels × ~100
/// bytes ≈ 1 MB — negligible on modern hardware.
class OrderBook {
public:
    /// Construct a book for a given tick range.
    ///
    /// @param base_price  Lowest representable price in ticks.
    /// @param num_levels  Number of tick levels above base_price.
    /// @param tick_size   Tick size in price units (e.g., 0.01 for equities).
    ///                    Stored for display/conversion only — all internal
    ///                    operations use integer ticks.
    OrderBook(PriceTicks base_price, std::size_t num_levels, double tick_size = 0.01)
        : base_price_(base_price),
          num_levels_(num_levels),
          tick_size_(tick_size),
          bid_levels_(num_levels),
          ask_levels_(num_levels) {
        for (std::size_t i = 0; i < num_levels; ++i) {
            PriceTicks p = base_price + static_cast<PriceTicks>(i);
            bid_levels_[i] = PriceLevel(p);
            ask_levels_[i] = PriceLevel(p);
        }
    }

    /// Add a limit order. If it crosses the spread, it matches immediately
    /// (aggressive). Any remaining quantity rests in the book (passive).
    ///
    /// Returns fills generated by the aggressive portion.
    std::vector<Fill> add_order(Order order) {
        std::vector<Fill> fills;
        stats_.total_orders++;

        // Aggressive matching: buy crosses ask, sell crosses bid
        if (order.side == Side::Buy) {
            while (order.remaining() > 0 && best_ask_ < num_levels_) {
                PriceTicks ask_price = base_price_ + static_cast<PriceTicks>(best_ask_);
                if (order.price < ask_price) break;
                ask_levels_[best_ask_].match(order, order.timestamp, fills);
                if (ask_levels_[best_ask_].empty()) {
                    stats_.active_ask_levels--;
                    advance_best_ask();
                }
            }
        } else {
            while (order.remaining() > 0 && best_bid_ < num_levels_) {
                PriceTicks bid_price = base_price_ + static_cast<PriceTicks>(best_bid_);
                if (order.price > bid_price) break;
                bid_levels_[best_bid_].match(order, order.timestamp, fills);
                if (bid_levels_[best_bid_].empty()) {
                    stats_.active_bid_levels--;
                    advance_best_bid();
                }
            }
        }

        stats_.total_fills += fills.size();

        // Rest any remaining quantity
        if (order.remaining() > 0) {
            auto idx = price_index(order.price);
            if (idx < num_levels_) {
                if (order.side == Side::Buy) {
                    if (bid_levels_[idx].empty()) stats_.active_bid_levels++;
                    bid_levels_[idx].add(order);
                    if (best_bid_ >= num_levels_ || idx > best_bid_ ||
                        (best_bid_ < num_levels_ &&
                         order.price > base_price_ + static_cast<PriceTicks>(best_bid_))) {
                        // Update best bid: highest price = largest index
                        best_bid_ = idx;
                    }
                } else {
                    if (ask_levels_[idx].empty()) stats_.active_ask_levels++;
                    ask_levels_[idx].add(order);
                    if (best_ask_ >= num_levels_ || idx < best_ask_) {
                        best_ask_ = idx;
                    }
                }
                order_index_[order.id] = {order.side, order.price};
                stats_.active_orders++;
            }
        }

        return fills;
    }

    /// Cancel an order by ID. Returns true if the order was found and cancelled.
    bool cancel_order(OrderId id) {
        auto it = order_index_.find(id);
        if (it == order_index_.end()) return false;

        auto [side, price] = it->second;
        auto idx = price_index(price);
        bool removed = false;

        if (side == Side::Buy) {
            removed = bid_levels_[idx].cancel(id);
            if (removed && bid_levels_[idx].empty()) {
                stats_.active_bid_levels--;
                if (idx == best_bid_) advance_best_bid();
            }
        } else {
            removed = ask_levels_[idx].cancel(id);
            if (removed && ask_levels_[idx].empty()) {
                stats_.active_ask_levels--;
                if (idx == best_ask_) advance_best_ask();
            }
        }

        if (removed) {
            order_index_.erase(it);
            stats_.active_orders--;
            stats_.total_cancels++;
        }
        return removed;
    }

    /// Current best bid and offer.
    [[nodiscard]] BBO bbo() const {
        BBO result;
        if (best_bid_ < num_levels_ && !bid_levels_[best_bid_].empty()) {
            result.bid_price = bid_levels_[best_bid_].price();
            result.bid_quantity = bid_levels_[best_bid_].total_quantity();
        }
        if (best_ask_ < num_levels_ && !ask_levels_[best_ask_].empty()) {
            result.ask_price = ask_levels_[best_ask_].price();
            result.ask_quantity = ask_levels_[best_ask_].total_quantity();
        }
        return result;
    }

    /// Depth snapshot: top N price levels on each side.
    struct DepthEntry {
        PriceTicks price;
        Quantity quantity;
        std::size_t order_count;
    };

    std::vector<DepthEntry> bid_depth(std::size_t n) const {
        return collect_depth(bid_levels_, best_bid_, n, /*descending=*/true);
    }

    std::vector<DepthEntry> ask_depth(std::size_t n) const {
        return collect_depth(ask_levels_, best_ask_, n, /*descending=*/false);
    }

    /// Convert integer ticks to display price.
    [[nodiscard]] double tick_to_price(PriceTicks ticks) const {
        return static_cast<double>(ticks) * tick_size_;
    }

    [[nodiscard]] const BookStats& stats() const { return stats_; }
    [[nodiscard]] double tick_size() const { return tick_size_; }
    [[nodiscard]] PriceTicks base_price() const { return base_price_; }
    [[nodiscard]] std::size_t num_levels() const { return num_levels_; }

private:
    std::size_t price_index(PriceTicks price) const {
        auto offset = price - base_price_;
        if (offset < 0) return num_levels_;  // out of range sentinel
        return static_cast<std::size_t>(offset);
    }

    void advance_best_bid() {
        // Walk down from current best bid to find next non-empty level
        if (best_bid_ >= num_levels_) return;
        while (best_bid_ > 0) {
            best_bid_--;
            if (!bid_levels_[best_bid_].empty()) return;
        }
        if (bid_levels_[0].empty()) best_bid_ = num_levels_;  // no bids
    }

    void advance_best_ask() {
        // Walk up from current best ask to find next non-empty level
        if (best_ask_ >= num_levels_) return;
        best_ask_++;
        while (best_ask_ < num_levels_) {
            if (!ask_levels_[best_ask_].empty()) return;
            best_ask_++;
        }
        // best_ask_ == num_levels_ means no asks
    }

    std::vector<DepthEntry> collect_depth(
        const std::vector<PriceLevel>& levels,
        std::size_t start,
        std::size_t n,
        bool descending
    ) const {
        std::vector<DepthEntry> result;
        if (start >= num_levels_) return result;
        result.reserve(n);

        std::size_t idx = start;
        while (result.size() < n && idx < num_levels_) {
            if (!levels[idx].empty()) {
                result.push_back(DepthEntry{
                    .price = levels[idx].price(),
                    .quantity = levels[idx].total_quantity(),
                    .order_count = levels[idx].order_count(),
                });
            }
            if (descending) {
                if (idx == 0) break;
                idx--;
            } else {
                idx++;
            }
        }
        return result;
    }

    PriceTicks base_price_;
    std::size_t num_levels_;
    double tick_size_;

    // Flat arrays indexed by (price - base_price). O(1) level lookup.
    // This replaces std::map<double> which has O(log n) lookup and
    // poor cache locality due to red-black tree pointer chasing.
    std::vector<PriceLevel> bid_levels_;
    std::vector<PriceLevel> ask_levels_;

    // Best bid = highest occupied bid index, best ask = lowest occupied ask index.
    // num_levels_ sentinel means "no orders on this side."
    std::size_t best_bid_{num_levels_};  // no bids initially
    std::size_t best_ask_{num_levels_};  // no asks initially

    // Order ID → (side, price) for O(1) cancel lookup.
    std::unordered_map<OrderId, std::pair<Side, PriceTicks>> order_index_;

    BookStats stats_;
};

}  // namespace orderbook
